In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import itertools

A. For each possible group defined by race, age, gender, location, and year, where:

● race is one of “Asian”, “Black”, “Hispanic”, “White”

● age is one of the buckets 15–19, 20–29, 30–39, 40–49, and 50+.

● gender is one of “female”, “male”

● location is a state patrol troop district

● and year is between 2010 and 2015, inclusive


report the following:

● the population of the group from census data, and

● the number of stops in that group from SOPP data.

In [105]:
races = ['Asian', 'Black', 'Hispanic', 'White']
age = ['15–19', '20–29', '30–39', '40–49', '50+']
age_bins = [15, 20, 30, 40, 50]
age_groups = [[4], [5, 6], [7, 8], [9, 10], [11,12,13,14,15,16,17,18]]
gender = ['F', 'M']
district = ['F4', 'C3', 'E5', 'H6', 'E4', 'H1', 'A4', 'G5', 'D1', 'A3', 'H5', 'E1',
 'G3', 'F1', 'B6', 'B5', 'A8', 'G1', 'G4', 'C1', 'A7', 'D5', 'H2', 'H3', 'C7',
 'E6', 'C5', 'B8', 'E3', 'F5', 'E2', 'C4', 'C6', 'A2', 'A6', 'F3', 'G2', 'B1',
 'B7', 'C2', 'D3', 'A1', 'D2', 'A5', 'A9', 'G7', 'F2', 'D4', 'B3', 'B2', 'H4',
 'D6', 'B4', 'G6', 'C8', 'E7', 'D7']
year = [2010, 2011, 2012, 2013, 2014, 2015]

final_df = pd.DataFrame(data=list(itertools.product(*[races,age,gender,district,year])), columns=['Race', 'Age', 'Gender', 'Location', 'Year'])
final_df

        Race    Age Gender Location  Year
0      Asian  15–19      F       F4  2010
1      Asian  15–19      F       F4  2011
2      Asian  15–19      F       F4  2012
3      Asian  15–19      F       F4  2013
4      Asian  15–19      F       F4  2014
...      ...    ...    ...      ...   ...
13675  White    50+      M       D7  2011
13676  White    50+      M       D7  2012
13677  White    50+      M       D7  2013
13678  White    50+      M       D7  2014
13679  White    50+      M       D7  2015

[13680 rows x 5 columns]

In [106]:
sopp_df = pd.DataFrame(pd.read_csv('NC-clean.csv', dtype={"county_name": "string", "district": "string"}))
sopp_df.head()

/home/vivienn/miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3145: DtypeWarning: Columns (3,7,23,24) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,id,state,stop_date,stop_time,location_raw,county_name,county_fips,fine_grained_location,police_department,driver_gender,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,search_basis,officer_id,drugs_related_stop,ethnicity,district
0,NC-2000-000001,NC,2000-01-01,00:01,NaN,<NA>,NaN,Unknown,NC State Highway Patrol,M,...,Search Incident to Arrest,Incident to Arrest,False,Arrest,True,NaN,NaN,NaN,N,<NA>
1,NC-2000-000002,NC,2000-01-01,00:01,NaN,<NA>,NaN,Unknown,NC State Highway Patrol,M,...,NaN,NaN,False,Written Warning,False,NaN,NaN,NaN,N,<NA>
2,NC-2000-000003,NC,2000-01-01,00:01,NaN,<NA>,NaN,Unknown,NC State Highway Patrol,F,...,NaN,NaN,False,Written Warning,False,NaN,NaN,NaN,N,<NA>
3,NC-2000-000004,NC,2000-01-01,00:02,NaN,<NA>,NaN,Unknown,NC State Highway Patrol,F,...,NaN,NaN,False,Citation,False,NaN,NaN,NaN,N,<NA>
4,NC-2000-000005,NC,2000-01-01,00:02,NaN,<NA>,NaN,Unknown,NC State Highway Patrol,F,...,NaN,NaN,False,No Action,False,NaN,NaN,NaN,N,<NA>

In [107]:
sopp_df['stop_year'] = sopp_df['stop_date'].str[:4].astype(int)
sopp_df_drop = sopp_df[(sopp_df['stop_year'].astype(int) >= 2010) & (sopp_df['stop_year'].astype(int) <= 2015)]
sopp_df_drop = sopp_df_drop[sopp_df_drop['district'] != '<NA>']
sopp_df_drop.head()

,id,state,stop_date,stop_time,location_raw,county_name,county_fips,fine_grained_location,police_department,driver_gender,...,search_type,contraband_found,stop_outcome,is_arrested,search_basis,officer_id,drugs_related_stop,ethnicity,district,stop_year
5121943,NC-2010-000001,NC,2010-01-01,NaN,A7,<NA>,NaN,NaN,NC State Highway Patrol,M,...,NaN,False,Citation,False,NaN,11362,NaN,N,A7,2010
5121944,NC-2010-000002,NC,2010-01-01,NaN,A7,<NA>,NaN,NaN,NC State Highway Patrol,F,...,NaN,False,Written Warning,False,NaN,11362,NaN,N,A7,2010
5121945,NC-2010-000003,NC,2010-01-01,NaN,A7,<NA>,NaN,NaN,NC State Highway Patrol,M,...,NaN,False,Written Warning,False,NaN,11362,NaN,N,A7,2010
5121946,NC-2010-000004,NC,2010-01-01,NaN,A7,<NA>,NaN,NaN,NC State Highway Patrol,M,...,NaN,False,Written Warning,False,NaN,11362,NaN,N,A7,2010
5121947,NC-2010-000005,NC,2010-01-01,NaN,A7,<NA>,NaN,NaN,NC State Highway Patrol,M,...,NaN,False,Written Warning,False,NaN,11362,NaN,N,A7,2010

In [108]:
sopp_df_drop.loc[(sopp_df_drop['driver_age'] >= 15) & (sopp_df_drop['driver_age'] < 20), 'driver_age_group'] = age[0]
sopp_df_drop.loc[(sopp_df_drop['driver_age'] >= 20) & (sopp_df_drop['driver_age'] < 30), 'driver_age_group'] = age[1]
sopp_df_drop.loc[(sopp_df_drop['driver_age'] >= 30) & (sopp_df_drop['driver_age'] < 40), 'driver_age_group'] = age[2]
sopp_df_drop.loc[(sopp_df_drop['driver_age'] >= 40) & (sopp_df_drop['driver_age'] < 50), 'driver_age_group'] = age[3]
sopp_df_drop.loc[(sopp_df_drop['driver_age'] >= 50), 'driver_age_group'] = age[4]

sopp_df_agg = sopp_df_drop.groupby(['driver_gender', 'driver_age_group', 'driver_race', 'district', 'stop_year']).agg(['count'])
sopp_df_agg.columns = sopp_df_agg.columns.get_level_values(0) + '_count'
sopp_df_agg = sopp_df_agg.reset_index()
sopp_df_agg.head()

,driver_gender,driver_age_group,driver_race,district,stop_year,id_count,state_count,stop_date_count,stop_time_count,location_raw_count,...,search_conducted_count,search_type_raw_count,search_type_count,contraband_found_count,stop_outcome_count,is_arrested_count,search_basis_count,officer_id_count,drugs_related_stop_count,ethnicity_count
0,F,15–19,Asian,A1,2010,1,1,1,0,1,...,1,0,0,1,1,1,0,1,0,1
1,F,15–19,Asian,A1,2011,1,1,1,0,1,...,1,0,0,1,1,1,0,1,0,1
2,F,15–19,Asian,A1,2012,1,1,1,0,1,...,1,0,0,1,1,1,0,1,0,1
3,F,15–19,Asian,A1,2015,2,2,2,0,2,...,2,0,0,2,2,2,0,2,0,2
4,F,15–19,Asian,A2,2013,2,2,2,0,2,...,2,0,0,2,2,2,0,2,0,2

In [109]:
sopp_df_agg_renamed = sopp_df_agg.rename(columns={'driver_gender': 'Gender', 'driver_race': 'Race', 'driver_age_group': 'Age', 'district': 'Location', 'stop_year': 'Year'})

In [110]:
sopp_df_agg_renamed

,Gender,Age,Race,Location,Year,id_count,state_count,stop_date_count,stop_time_count,location_raw_count,...,search_conducted_count,search_type_raw_count,search_type_count,contraband_found_count,stop_outcome_count,is_arrested_count,search_basis_count,officer_id_count,drugs_related_stop_count,ethnicity_count
0,F,15–19,Asian,A1,2010,1,1,1,0,1,...,1,0,0,1,1,1,0,1,0,1
1,F,15–19,Asian,A1,2011,1,1,1,0,1,...,1,0,0,1,1,1,0,1,0,1
2,F,15–19,Asian,A1,2012,1,1,1,0,1,...,1,0,0,1,1,1,0,1,0,1
3,F,15–19,Asian,A1,2015,2,2,2,0,2,...,2,0,0,2,2,2,0,2,0,2
4,F,15–19,Asian,A2,2013,2,2,2,0,2,...,2,0,0,2,2,2,0,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16216,M,50+,White,H6,2011,917,917,917,0,917,...,917,1,1,917,917,917,1,917,1,917
16217,M,50+,White,H6,2012,859,859,859,0,859,...,859,1,1,859,859,859,1,859,0,859
16218,M,50+,White,H6,2013,721,721,721,2,721,...,721,5,5,721,721,721,5,721,0,721
16219,M,50+,White,H6,2014,452,452,452,0,452,...,452,0,0,452,452,452,0,452,0,452
16220,M,50+,White,H6,2015,346,346,346,0,346,...,346,0,0,346,346,346,0,346,0,346

In [111]:
final_df = final_df.merge(sopp_df_agg_renamed, on=['Gender', 'Race', 'Age', 'Location', 'Year'], how='outer')[['Race', 'Age', 'Gender', 'Location', 'Year', 'id_count']]
final_df = final_df.rename(columns={'id_count': 'Count'})
final_df.head()

    Race    Age Gender Location  Year  Count
0  Asian  15–19      F       F4  2010    5.0
1  Asian  15–19      F       F4  2011    5.0
2  Asian  15–19      F       F4  2012    2.0
3  Asian  15–19      F       F4  2013    3.0
4  Asian  15–19      F       F4  2014    3.0

In [112]:
districts = pd.DataFrame(pd.read_csv('districts.txt'))
districts.head()

  state       county_name  county_fips                     district
0    IA      Adair County        19001  Iowa State Patrol - Dist 03
1    IA      Adams County        19003  Iowa State Patrol - Dist 03
2    IA  Allamakee County        19005  Iowa State Patrol - Dist 10
3    IA  Appanoose County        19007  Iowa State Patrol - Dist 02
4    IA    Audubon County        19009  Iowa State Patrol - Dist 04

In [113]:
census = pd.DataFrame(pd.read_csv('cc-est2015-alldata.csv'))
census.head()

,SUMLEV,STATE,COUNTY,STNAME,CTYNAME,YEAR,AGEGRP,TOT_POP,TOT_MALE,TOT_FEMALE,...,HWAC_MALE,HWAC_FEMALE,HBAC_MALE,HBAC_FEMALE,HIAC_MALE,HIAC_FEMALE,HAAC_MALE,HAAC_FEMALE,HNAC_MALE,HNAC_FEMALE
0,50,1,1,Alabama,Autauga County,1,0,54571,26569,28002,...,607,538,57,48,26,32,9,11,19,10
1,50,1,1,Alabama,Autauga County,1,1,3579,1866,1713,...,77,56,9,5,4,1,0,0,2,1
2,50,1,1,Alabama,Autauga County,1,2,3991,2001,1990,...,64,66,2,3,2,7,2,3,2,0
3,50,1,1,Alabama,Autauga County,1,3,4290,2171,2119,...,51,57,13,7,5,5,2,1,1,1
4,50,1,1,Alabama,Autauga County,1,4,4290,2213,2077,...,48,44,7,5,0,2,2,1,3,1

In [114]:
states = pd.DataFrame(pd.read_csv('states.csv'))
states = states.rename(columns={'State': 'STNAME'})
states = states.drop(columns='Abbrev')
states.head()

       STNAME Code
0     Alabama   AL
1      Alaska   AK
2     Arizona   AZ
3    Arkansas   AR
4  California   CA

In [115]:
census_w_code = census.merge(states, on='STNAME')
census_w_code.head()

,SUMLEV,STATE,COUNTY,STNAME,CTYNAME,YEAR,AGEGRP,TOT_POP,TOT_MALE,TOT_FEMALE,...,HWAC_FEMALE,HBAC_MALE,HBAC_FEMALE,HIAC_MALE,HIAC_FEMALE,HAAC_MALE,HAAC_FEMALE,HNAC_MALE,HNAC_FEMALE,Code
0,50,1,1,Alabama,Autauga County,1,0,54571,26569,28002,...,538,57,48,26,32,9,11,19,10,AL
1,50,1,1,Alabama,Autauga County,1,1,3579,1866,1713,...,56,9,5,4,1,0,0,2,1,AL
2,50,1,1,Alabama,Autauga County,1,2,3991,2001,1990,...,66,2,3,2,7,2,3,2,0,AL
3,50,1,1,Alabama,Autauga County,1,3,4290,2171,2119,...,57,13,7,5,5,2,1,1,1,AL
4,50,1,1,Alabama,Autauga County,1,4,4290,2213,2077,...,44,7,5,0,2,2,1,3,1,AL

In [116]:
districts=districts.rename(columns={'county_name': 'CTYNAME', 'state':'Code'})
districts.head()

  Code           CTYNAME  county_fips                     district
0   IA      Adair County        19001  Iowa State Patrol - Dist 03
1   IA      Adams County        19003  Iowa State Patrol - Dist 03
2   IA  Allamakee County        19005  Iowa State Patrol - Dist 10
3   IA  Appanoose County        19007  Iowa State Patrol - Dist 02
4   IA    Audubon County        19009  Iowa State Patrol - Dist 04

In [117]:
census_w_district = census_w_code.merge(districts, on=['CTYNAME', 'Code'], how='outer')
census_w_district.head()

,SUMLEV,STATE,COUNTY,STNAME,CTYNAME,YEAR,AGEGRP,TOT_POP,TOT_MALE,TOT_FEMALE,...,HBAC_FEMALE,HIAC_MALE,HIAC_FEMALE,HAAC_MALE,HAAC_FEMALE,HNAC_MALE,HNAC_FEMALE,Code,county_fips,district
0,50,1,1,Alabama,Autauga County,1,0,54571,26569,28002,...,48,26,32,9,11,19,10,AL,NaN,NaN
1,50,1,1,Alabama,Autauga County,1,1,3579,1866,1713,...,5,4,1,0,0,2,1,AL,NaN,NaN
2,50,1,1,Alabama,Autauga County,1,2,3991,2001,1990,...,3,2,7,2,3,2,0,AL,NaN,NaN
3,50,1,1,Alabama,Autauga County,1,3,4290,2171,2119,...,7,5,5,2,1,1,1,AL,NaN,NaN
4,50,1,1,Alabama,Autauga County,1,4,4290,2213,2077,...,5,0,2,2,1,3,1,AL,NaN,NaN

In [118]:
census_agg = census_w_district.groupby(['district', 'AGEGRP', 'YEAR']).agg('sum')[['AA_MALE', 'AA_FEMALE', 'BA_MALE', 'BA_FEMALE', 'H_MALE', 'H_FEMALE', 'WA_MALE', 'WA_FEMALE']]
census_agg.head()

                      AA_MALE  AA_FEMALE  BA_MALE  BA_FEMALE  H_MALE  \
district AGEGRP YEAR
A1       0      1         119        253     1129       1134    1605
                2         119        253     1129       1134    1605
                3         117        258     1132       1139    1606
                4         121        260     1153       1175    1609
                5         133        265     1194       1190    1659

                      H_FEMALE  WA_MALE  WA_FEMALE
district AGEGRP YEAR
A1       0      1         1309    26780      26834
                2         1309    26780      26834
                3         1329    26859      26914
                4         1402    26932      27178
                5         1496    26995      27372

In [119]:
for i, row in final_df.iterrows():
    race = row.Race
    if race == 'Asian':
        census_col = 'AA_'
    elif race == 'Black':
        census_col = 'BA_'
    elif race == 'Hispanic':
        census_col = 'H_'
    elif race == 'White':
        census_col = 'WA_'
    else:
        print('Unknown race')
        break
    
    gender = row.Gender
    if gender == 'F':
        census_col += 'FEMALE'
    elif gender == 'M':
        census_col += 'MALE'
    else:
        print('Unknown gender')
        break
        
    age_idx = age.index(row.Age)
    census_age_groups = age_groups[age_idx]
    district = row.Location
    year = row.Year
    census_year = year - 2007
    pop_sum = 0
    for a in census_age_groups:
        id_search = np.where((census_agg.reset_index()[['district', 'AGEGRP', 'YEAR']] == [district, a, census_year]).all(axis=1))[0]
        if len(id_search) < 1:
            print('Could not find: ', district, a, census_year)
            continue
        else:
            row_id = id_search[0]
            pop_sum += census_agg.iloc[row_id][census_col]
    final_df.loc[i, 'Population'] = pop_sum
    if i % 1000 == 0:
        print(i)
#     final_df.iloc[i]['Population'] = pop_sum
#     break

0
Could not find:  A9 4 3
Could not find:  A9 4 4
Could not find:  A9 4 5
Could not find:  A9 4 6
Could not find:  A9 4 7
Could not find:  A9 4 8
Could not find:  G7 4 3
Could not find:  G7 4 4
Could not find:  G7 4 5
Could not find:  G7 4 6
Could not find:  G7 4 7
Could not find:  G7 4 8
Could not find:  A9 4 3
Could not find:  A9 4 4
Could not find:  A9 4 5
Could not find:  A9 4 6
Could not find:  A9 4 7
Could not find:  A9 4 8
Could not find:  G7 4 3
Could not find:  G7 4 4
Could not find:  G7 4 5
Could not find:  G7 4 6
Could not find:  G7 4 7
Could not find:  G7 4 8
Could not find:  A9 5 3
Could not find:  A9 6 3
Could not find:  A9 5 4
Could not find:  A9 6 4
Could not find:  A9 5 5
Could not find:  A9 6 5
Could not find:  A9 5 6
Could not find:  A9 6 6
Could not find:  A9 5 7
Could not find:  A9 6 7
Could not find:  A9 5 8
Could not find:  A9 6 8
Could not find:  G7 5 3
Could not find:  G7 6 3
Could not find:  G7 5 4
Could not find:  G7 6 4
Could not find:  G7 5 5
Could not find:  G7 6 5
Could not find:  G7 5 6
Could not find:  G7 6 6
Could not find:  G7 5 7
Could not find:  G7 6 7
Could not find:  G7 5 8
Could not find:  G7 6 8
1000
Could not find:  A9 5 3
Could not find:  A9 6 3
Could not find:  A9 5 4
Could not find:  A9 6 4
Could not find:  A9 5 5
Could not find:  A9 6 5
Could not find:  A9 5 6
Could not find:  A9 6 6
Could not find:  A9 5 7
Could not find:  A9 6 7
Could not find:  A9 5 8
Could not find:  A9 6 8
Could not find:  G7 5 3
Could not find:  G7 6 3
Could not find:  G7 5 4
Could not find:  G7 6 4
Could not find:  G7 5 5
Could not find:  G7 6 5
Could not find:  G7 5 6
Could not find:  G7 6 6
Could not find:  G7 5 7
Could not find:  G7 6 7
Could not find:  G7 5 8
Could not find:  G7 6 8
Could not find:  A9 7 3
Could not find:  A9 8 3
Could not find:  A9 7 4
Could not find:  A9 8 4
Could not find:  A9 7 5
Could not find:  A9 8 5
Could not find:  A9 7 6
Could not find:  A9 8 6
Could not find:  A9 7 7
Could not find:  A9 8 7
Could not find:  A9 7 8
Could not find:  A9 8 8
Could not find:  G7 7 3
Could not find:  G7 8 3
Could not find:  G7 7 4
Could not find:  G7 8 4
Could not find:  G7 7 5
Could not find:  G7 8 5
Could not find:  G7 7 6
Could not find:  G7 8 6
Could not find:  G7 7 7
Could not find:  G7 8 7
Could not find:  G7 7 8
Could not find:  G7 8 8
Could not find:  A9 7 3
Could not find:  A9 8 3
Could not find:  A9 7 4
Could not find:  A9 8 4
Could not find:  A9 7 5
Could not find:  A9 8 5
Could not find:  A9 7 6
Could not find:  A9 8 6
Could not find:  A9 7 7
Could not find:  A9 8 7
Could not find:  A9 7 8
Could not find:  A9 8 8
Could not find:  G7 7 3
Could not find:  G7 8 3
Could not find:  G7 7 4
Could not find:  G7 8 4
Could not find:  G7 7 5
Could not find:  G7 8 5
Could not find:  G7 7 6
Could not find:  G7 8 6
Could not find:  G7 7 7
Could not find:  G7 8 7
Could not find:  G7 7 8
Could not find:  G7 8 8
2000
Could not find:  A9 9 3
Could not find:  A9 10 3
Could not find:  A9 9 4
Could not find:  A9 10 4
Could not find:  A9 9 5
Could not find:  A9 10 5
Could not find:  A9 9 6
Could not find:  A9 10 6
Could not find:  A9 9 7
Could not find:  A9 10 7
Could not find:  A9 9 8
Could not find:  A9 10 8
Could not find:  G7 9 3
Could not find:  G7 10 3
Could not find:  G7 9 4
Could not find:  G7 10 4
Could not find:  G7 9 5
Could not find:  G7 10 5
Could not find:  G7 9 6
Could not find:  G7 10 6
Could not find:  G7 9 7
Could not find:  G7 10 7
Could not find:  G7 9 8
Could not find:  G7 10 8
Could not find:  A9 9 3
Could not find:  A9 10 3
Could not find:  A9 9 4
Could not find:  A9 10 4
Could not find:  A9 9 5
Could not find:  A9 10 5
Could not find:  A9 9 6
Could not find:  A9 10 6
Could not find:  A9 9 7
Could not find:  A9 10 7
Could not find:  A9 9 8
Could not find:  A9 10 8
Could not find:  G7 9 3
Could not find:  G7 10 3
Could not find:  G7 9 4
Could not find:  G7 10 4
Could not find:  G7 9 5
Could not find:  G7 10 5
Could not find:  G7 9 6
Could not find:  G7 10 6
Could not find:  G7 9 7
Could not find:  G7 10 7
Could not find:  G7 9 8
Could not find:  G7 10 8
Could not find:  A9 11 3
Could not find:  A9 12 3
Could not find:  A9 13 3
Could not find:  A9 14 3
Could not find:  A9 15 3
Could not find:  A9 16 3
Could not find:  A9 17 3
Could not find:  A9 18 3
3000
Could not find:  A9 11 4
Could not find:  A9 12 4
Could not find:  A9 13 4
Could not find:  A9 14 4
Could not find:  A9 15 4
Could not find:  A9 16 4
Could not find:  A9 17 4
Could not find:  A9 18 4
Could not find:  A9 11 5
Could not find:  A9 12 5
Could not find:  A9 13 5
Could not find:  A9 14 5
Could not find:  A9 15 5
Could not find:  A9 16 5
Could not find:  A9 17 5
Could not find:  A9 18 5
Could not find:  A9 11 6
Could not find:  A9 12 6
Could not find:  A9 13 6
Could not find:  A9 14 6
Could not find:  A9 15 6
Could not find:  A9 16 6
Could not find:  A9 17 6
Could not find:  A9 18 6
Could not find:  A9 11 7
Could not find:  A9 12 7
Could not find:  A9 13 7
Could not find:  A9 14 7
Could not find:  A9 15 7
Could not find:  A9 16 7
Could not find:  A9 17 7
Could not find:  A9 18 7
Could not find:  A9 11 8
Could not find:  A9 12 8
Could not find:  A9 13 8
Could not find:  A9 14 8
Could not find:  A9 15 8
Could not find:  A9 16 8
Could not find:  A9 17 8
Could not find:  A9 18 8
Could not find:  G7 11 3
Could not find:  G7 12 3
Could not find:  G7 13 3
Could not find:  G7 14 3
Could not find:  G7 15 3
Could not find:  G7 16 3
Could not find:  G7 17 3
Could not find:  G7 18 3
Could not find:  G7 11 4
Could not find:  G7 12 4
Could not find:  G7 13 4
Could not find:  G7 14 4
Could not find:  G7 15 4
Could not find:  G7 16 4
Could not find:  G7 17 4
Could not find:  G7 18 4
Could not find:  G7 11 5
Could not find:  G7 12 5
Could not find:  G7 13 5
Could not find:  G7 14 5
Could not find:  G7 15 5
Could not find:  G7 16 5
Could not find:  G7 17 5
Could not find:  G7 18 5
Could not find:  G7 11 6
Could not find:  G7 12 6
Could not find:  G7 13 6
Could not find:  G7 14 6
Could not find:  G7 15 6
Could not find:  G7 16 6
Could not find:  G7 17 6
Could not find:  G7 18 6
Could not find:  G7 11 7
Could not find:  G7 12 7
Could not find:  G7 13 7
Could not find:  G7 14 7
Could not find:  G7 15 7
Could not find:  G7 16 7
Could not find:  G7 17 7
Could not find:  G7 18 7
Could not find:  G7 11 8
Could not find:  G7 12 8
Could not find:  G7 13 8
Could not find:  G7 14 8
Could not find:  G7 15 8
Could not find:  G7 16 8
Could not find:  G7 17 8
Could not find:  G7 18 8
Could not find:  A9 11 3
Could not find:  A9 12 3
Could not find:  A9 13 3
Could not find:  A9 14 3
Could not find:  A9 15 3
Could not find:  A9 16 3
Could not find:  A9 17 3
Could not find:  A9 18 3
Could not find:  A9 11 4
Could not find:  A9 12 4
Could not find:  A9 13 4
Could not find:  A9 14 4
Could not find:  A9 15 4
Could not find:  A9 16 4
Could not find:  A9 17 4
Could not find:  A9 18 4
Could not find:  A9 11 5
Could not find:  A9 12 5
Could not find:  A9 13 5
Could not find:  A9 14 5
Could not find:  A9 15 5
Could not find:  A9 16 5
Could not find:  A9 17 5
Could not find:  A9 18 5
Could not find:  A9 11 6
Could not find:  A9 12 6
Could not find:  A9 13 6
Could not find:  A9 14 6
Could not find:  A9 15 6
Could not find:  A9 16 6
Could not find:  A9 17 6
Could not find:  A9 18 6
Could not find:  A9 11 7
Could not find:  A9 12 7
Could not find:  A9 13 7
Could not find:  A9 14 7
Could not find:  A9 15 7
Could not find:  A9 16 7
Could not find:  A9 17 7
Could not find:  A9 18 7
Could not find:  A9 11 8
Could not find:  A9 12 8
Could not find:  A9 13 8
Could not find:  A9 14 8
Could not find:  A9 15 8
Could not find:  A9 16 8
Could not find:  A9 17 8
Could not find:  A9 18 8
Could not find:  G7 11 3
Could not find:  G7 12 3
Could not find:  G7 13 3
Could not find:  G7 14 3
Could not find:  G7 15 3
Could not find:  G7 16 3
Could not find:  G7 17 3
Could not find:  G7 18 3
Could not find:  G7 11 4
Could not find:  G7 12 4
Could not find:  G7 13 4
Could not find:  G7 14 4
Could not find:  G7 15 4
Could not find:  G7 16 4
Could not find:  G7 17 4
Could not find:  G7 18 4
Could not find:  G7 11 5
Could not find:  G7 12 5
Could not find:  G7 13 5
Could not find:  G7 14 5
Could not find:  G7 15 5
Could not find:  G7 16 5
Could not find:  G7 17 5
Could not find:  G7 18 5
Could not find:  G7 11 6
Could not find:  G7 12 6
Could not find:  G7 13 6
Could not find:  G7 14 6
Could not find:  G7 15 6
Could not find:  G7 16 6
Could not find:  G7 17 6
Could not find:  G7 18 6
Could not find:  G7 11 7
Could not find:  G7 12 7
Could not find:  G7 13 7
Could not find:  G7 14 7
Could not find:  G7 15 7
Could not find:  G7 16 7
Could not find:  G7 17 7
Could not find:  G7 18 7
Could not find:  G7 11 8
Could not find:  G7 12 8
Could not find:  G7 13 8
Could not find:  G7 14 8
Could not find:  G7 15 8
Could not find:  G7 16 8
Could not find:  G7 17 8
Could not find:  G7 18 8
Could not find:  A9 4 3
Could not find:  A9 4 4
Could not find:  A9 4 5
Could not find:  A9 4 6
Could not find:  A9 4 7
Could not find:  A9 4 8
Could not find:  G7 4 3
Could not find:  G7 4 4
Could not find:  G7 4 5
Could not find:  G7 4 6
Could not find:  G7 4 7
Could not find:  G7 4 8
4000
Could not find:  A9 4 3
Could not find:  A9 4 4
Could not find:  A9 4 5
Could not find:  A9 4 6
Could not find:  A9 4 7
Could not find:  A9 4 8
Could not find:  G7 4 3
Could not find:  G7 4 4
Could not find:  G7 4 5
Could not find:  G7 4 6
Could not find:  G7 4 7
Could not find:  G7 4 8
Could not find:  A9 5 3
Could not find:  A9 6 3
Could not find:  A9 5 4
Could not find:  A9 6 4
Could not find:  A9 5 5
Could not find:  A9 6 5
Could not find:  A9 5 6
Could not find:  A9 6 6
Could not find:  A9 5 7
Could not find:  A9 6 7
Could not find:  A9 5 8
Could not find:  A9 6 8
Could not find:  G7 5 3
Could not find:  G7 6 3
Could not find:  G7 5 4
Could not find:  G7 6 4
Could not find:  G7 5 5
Could not find:  G7 6 5
Could not find:  G7 5 6
Could not find:  G7 6 6
Could not find:  G7 5 7
Could not find:  G7 6 7
Could not find:  G7 5 8
Could not find:  G7 6 8
Could not find:  A9 5 3
Could not find:  A9 6 3
Could not find:  A9 5 4
Could not find:  A9 6 4
Could not find:  A9 5 5
Could not find:  A9 6 5
Could not find:  A9 5 6
Could not find:  A9 6 6
Could not find:  A9 5 7
Could not find:  A9 6 7
Could not find:  A9 5 8
Could not find:  A9 6 8
Could not find:  G7 5 3
Could not find:  G7 6 3
Could not find:  G7 5 4
Could not find:  G7 6 4
Could not find:  G7 5 5
Could not find:  G7 6 5
Could not find:  G7 5 6
Could not find:  G7 6 6
Could not find:  G7 5 7
Could not find:  G7 6 7
Could not find:  G7 5 8
Could not find:  G7 6 8
5000
Could not find:  A9 7 3
Could not find:  A9 8 3
Could not find:  A9 7 4
Could not find:  A9 8 4
Could not find:  A9 7 5
Could not find:  A9 8 5
Could not find:  A9 7 6
Could not find:  A9 8 6
Could not find:  A9 7 7
Could not find:  A9 8 7
Could not find:  A9 7 8
Could not find:  A9 8 8
Could not find:  G7 7 3
Could not find:  G7 8 3
Could not find:  G7 7 4
Could not find:  G7 8 4
Could not find:  G7 7 5
Could not find:  G7 8 5
Could not find:  G7 7 6
Could not find:  G7 8 6
Could not find:  G7 7 7
Could not find:  G7 8 7
Could not find:  G7 7 8
Could not find:  G7 8 8
Could not find:  A9 7 3
Could not find:  A9 8 3
Could not find:  A9 7 4
Could not find:  A9 8 4
Could not find:  A9 7 5
Could not find:  A9 8 5
Could not find:  A9 7 6
Could not find:  A9 8 6
Could not find:  A9 7 7
Could not find:  A9 8 7
Could not find:  A9 7 8
Could not find:  A9 8 8
Could not find:  G7 7 3
Could not find:  G7 8 3
Could not find:  G7 7 4
Could not find:  G7 8 4
Could not find:  G7 7 5
Could not find:  G7 8 5
Could not find:  G7 7 6
Could not find:  G7 8 6
Could not find:  G7 7 7
Could not find:  G7 8 7
Could not find:  G7 7 8
Could not find:  G7 8 8
Could not find:  A9 9 3
Could not find:  A9 10 3
Could not find:  A9 9 4
Could not find:  A9 10 4
Could not find:  A9 9 5
Could not find:  A9 10 5
Could not find:  A9 9 6
Could not find:  A9 10 6
Could not find:  A9 9 7
Could not find:  A9 10 7
Could not find:  A9 9 8
Could not find:  A9 10 8
Could not find:  G7 9 3
Could not find:  G7 10 3
Could not find:  G7 9 4
Could not find:  G7 10 4
Could not find:  G7 9 5
Could not find:  G7 10 5
Could not find:  G7 9 6
Could not find:  G7 10 6
Could not find:  G7 9 7
Could not find:  G7 10 7
Could not find:  G7 9 8
Could not find:  G7 10 8
6000
Could not find:  A9 9 3
Could not find:  A9 10 3
Could not find:  A9 9 4
Could not find:  A9 10 4
Could not find:  A9 9 5
Could not find:  A9 10 5
Could not find:  A9 9 6
Could not find:  A9 10 6
Could not find:  A9 9 7
Could not find:  A9 10 7
Could not find:  A9 9 8
Could not find:  A9 10 8
Could not find:  G7 9 3
Could not find:  G7 10 3
Could not find:  G7 9 4
Could not find:  G7 10 4
Could not find:  G7 9 5
Could not find:  G7 10 5
Could not find:  G7 9 6
Could not find:  G7 10 6
Could not find:  G7 9 7
Could not find:  G7 10 7
Could not find:  G7 9 8
Could not find:  G7 10 8
Could not find:  A9 11 3
Could not find:  A9 12 3
Could not find:  A9 13 3
Could not find:  A9 14 3
Could not find:  A9 15 3
Could not find:  A9 16 3
Could not find:  A9 17 3
Could not find:  A9 18 3
Could not find:  A9 11 4
Could not find:  A9 12 4
Could not find:  A9 13 4
Could not find:  A9 14 4
Could not find:  A9 15 4
Could not find:  A9 16 4
Could not find:  A9 17 4
Could not find:  A9 18 4
Could not find:  A9 11 5
Could not find:  A9 12 5
Could not find:  A9 13 5
Could not find:  A9 14 5
Could not find:  A9 15 5
Could not find:  A9 16 5
Could not find:  A9 17 5
Could not find:  A9 18 5
Could not find:  A9 11 6
Could not find:  A9 12 6
Could not find:  A9 13 6
Could not find:  A9 14 6
Could not find:  A9 15 6
Could not find:  A9 16 6
Could not find:  A9 17 6
Could not find:  A9 18 6
Could not find:  A9 11 7
Could not find:  A9 12 7
Could not find:  A9 13 7
Could not find:  A9 14 7
Could not find:  A9 15 7
Could not find:  A9 16 7
Could not find:  A9 17 7
Could not find:  A9 18 7
Could not find:  A9 11 8
Could not find:  A9 12 8
Could not find:  A9 13 8
Could not find:  A9 14 8
Could not find:  A9 15 8
Could not find:  A9 16 8
Could not find:  A9 17 8
Could not find:  A9 18 8
Could not find:  G7 11 3
Could not find:  G7 12 3
Could not find:  G7 13 3
Could not find:  G7 14 3
Could not find:  G7 15 3
Could not find:  G7 16 3
Could not find:  G7 17 3
Could not find:  G7 18 3
Could not find:  G7 11 4
Could not find:  G7 12 4
Could not find:  G7 13 4
Could not find:  G7 14 4
Could not find:  G7 15 4
Could not find:  G7 16 4
Could not find:  G7 17 4
Could not find:  G7 18 4
Could not find:  G7 11 5
Could not find:  G7 12 5
Could not find:  G7 13 5
Could not find:  G7 14 5
Could not find:  G7 15 5
Could not find:  G7 16 5
Could not find:  G7 17 5
Could not find:  G7 18 5
Could not find:  G7 11 6
Could not find:  G7 12 6
Could not find:  G7 13 6
Could not find:  G7 14 6
Could not find:  G7 15 6
Could not find:  G7 16 6
Could not find:  G7 17 6
Could not find:  G7 18 6
Could not find:  G7 11 7
Could not find:  G7 12 7
Could not find:  G7 13 7
Could not find:  G7 14 7
Could not find:  G7 15 7
Could not find:  G7 16 7
Could not find:  G7 17 7
Could not find:  G7 18 7
Could not find:  G7 11 8
Could not find:  G7 12 8
Could not find:  G7 13 8
Could not find:  G7 14 8
Could not find:  G7 15 8
Could not find:  G7 16 8
Could not find:  G7 17 8
Could not find:  G7 18 8
Could not find:  A9 11 3
Could not find:  A9 12 3
Could not find:  A9 13 3
Could not find:  A9 14 3
Could not find:  A9 15 3
Could not find:  A9 16 3
Could not find:  A9 17 3
Could not find:  A9 18 3
Could not find:  A9 11 4
Could not find:  A9 12 4
Could not find:  A9 13 4
Could not find:  A9 14 4
Could not find:  A9 15 4
Could not find:  A9 16 4
Could not find:  A9 17 4
Could not find:  A9 18 4
Could not find:  A9 11 5
Could not find:  A9 12 5
Could not find:  A9 13 5
Could not find:  A9 14 5
Could not find:  A9 15 5
Could not find:  A9 16 5
Could not find:  A9 17 5
Could not find:  A9 18 5
Could not find:  A9 11 6
Could not find:  A9 12 6
Could not find:  A9 13 6
Could not find:  A9 14 6
Could not find:  A9 15 6
Could not find:  A9 16 6
Could not find:  A9 17 6
Could not find:  A9 18 6
Could not find:  A9 11 7
Could not find:  A9 12 7
Could not find:  A9 13 7
Could not find:  A9 14 7
Could not find:  A9 15 7
Could not find:  A9 16 7
Could not find:  A9 17 7
Could not find:  A9 18 7
Could not find:  A9 11 8
Could not find:  A9 12 8
Could not find:  A9 13 8
Could not find:  A9 14 8
Could not find:  A9 15 8
Could not find:  A9 16 8
Could not find:  A9 17 8
Could not find:  A9 18 8
Could not find:  G7 11 3
Could not find:  G7 12 3
Could not find:  G7 13 3
Could not find:  G7 14 3
Could not find:  G7 15 3
Could not find:  G7 16 3
Could not find:  G7 17 3
Could not find:  G7 18 3
Could not find:  G7 11 4
Could not find:  G7 12 4
Could not find:  G7 13 4
Could not find:  G7 14 4
Could not find:  G7 15 4
Could not find:  G7 16 4
Could not find:  G7 17 4
Could not find:  G7 18 4
Could not find:  G7 11 5
Could not find:  G7 12 5
Could not find:  G7 13 5
Could not find:  G7 14 5
Could not find:  G7 15 5
Could not find:  G7 16 5
Could not find:  G7 17 5
Could not find:  G7 18 5
Could not find:  G7 11 6
Could not find:  G7 12 6
Could not find:  G7 13 6
Could not find:  G7 14 6
Could not find:  G7 15 6
Could not find:  G7 16 6
Could not find:  G7 17 6
Could not find:  G7 18 6
Could not find:  G7 11 7
Could not find:  G7 12 7
Could not find:  G7 13 7
Could not find:  G7 14 7
Could not find:  G7 15 7
Could not find:  G7 16 7
Could not find:  G7 17 7
Could not find:  G7 18 7
Could not find:  G7 11 8
Could not find:  G7 12 8
Could not find:  G7 13 8
Could not find:  G7 14 8
Could not find:  G7 15 8
Could not find:  G7 16 8
Could not find:  G7 17 8
Could not find:  G7 18 8
7000
Could not find:  A9 4 3
Could not find:  A9 4 4
Could not find:  A9 4 5
Could not find:  A9 4 6
Could not find:  A9 4 7
Could not find:  A9 4 8
Could not find:  G7 4 3
Could not find:  G7 4 4
Could not find:  G7 4 5
Could not find:  G7 4 6
Could not find:  G7 4 7
Could not find:  G7 4 8
Could not find:  A9 4 3
Could not find:  A9 4 4
Could not find:  A9 4 5
Could not find:  A9 4 6
Could not find:  A9 4 7
Could not find:  A9 4 8
Could not find:  G7 4 3
Could not find:  G7 4 4
Could not find:  G7 4 5
Could not find:  G7 4 6
Could not find:  G7 4 7
Could not find:  G7 4 8
Could not find:  A9 5 3
Could not find:  A9 6 3
Could not find:  A9 5 4
Could not find:  A9 6 4
Could not find:  A9 5 5
Could not find:  A9 6 5
Could not find:  A9 5 6
Could not find:  A9 6 6
Could not find:  A9 5 7
Could not find:  A9 6 7
Could not find:  A9 5 8
Could not find:  A9 6 8
Could not find:  G7 5 3
Could not find:  G7 6 3
Could not find:  G7 5 4
Could not find:  G7 6 4
Could not find:  G7 5 5
Could not find:  G7 6 5
Could not find:  G7 5 6
Could not find:  G7 6 6
Could not find:  G7 5 7
Could not find:  G7 6 7
Could not find:  G7 5 8
Could not find:  G7 6 8
8000
Could not find:  A9 5 3
Could not find:  A9 6 3
Could not find:  A9 5 4
Could not find:  A9 6 4
Could not find:  A9 5 5
Could not find:  A9 6 5
Could not find:  A9 5 6
Could not find:  A9 6 6
Could not find:  A9 5 7
Could not find:  A9 6 7
Could not find:  A9 5 8
Could not find:  A9 6 8
Could not find:  G7 5 3
Could not find:  G7 6 3
Could not find:  G7 5 4
Could not find:  G7 6 4
Could not find:  G7 5 5
Could not find:  G7 6 5
Could not find:  G7 5 6
Could not find:  G7 6 6
Could not find:  G7 5 7
Could not find:  G7 6 7
Could not find:  G7 5 8
Could not find:  G7 6 8
Could not find:  A9 7 3
Could not find:  A9 8 3
Could not find:  A9 7 4
Could not find:  A9 8 4
Could not find:  A9 7 5
Could not find:  A9 8 5
Could not find:  A9 7 6
Could not find:  A9 8 6
Could not find:  A9 7 7
Could not find:  A9 8 7
Could not find:  A9 7 8
Could not find:  A9 8 8
Could not find:  G7 7 3
Could not find:  G7 8 3
Could not find:  G7 7 4
Could not find:  G7 8 4
Could not find:  G7 7 5
Could not find:  G7 8 5
Could not find:  G7 7 6
Could not find:  G7 8 6
Could not find:  G7 7 7

In [61]:
district

'A9'

In [62]:
a

9

In [63]:
census_year

5

In [64]:
census_agg[census_agg['district'] == district]

KeyError: 'district'

In [125]:
sopp_df_agg = sopp_df_agg.reset_index()

In [81]:
sopp_df_agg['driver_age_group'] = np.clip(np.digitize(sopp_df_agg.driver_age, age_bins, right=True), 0, 4)

In [80]:
np.clip(np.digitize(sopp_df_agg.driver_age, age_bins, right=True), 0, 4)

array([0, 0, 0, ..., 4, 4, 4])

In [77]:
age_bins = [15, 20, 30, 40, 50]

In [49]:
np.where((census_agg.reset_index()[['district', 'AGEGRP', 'YEAR']] == [district, a, census_year]).all(axis=1))[0][0]

6265

In [48]:
census_agg.iloc[6265]

AA_MALE       145
AA_FEMALE     136
BA_MALE       955
BA_FEMALE     872
H_MALE        591
H_FEMALE      510
WA_MALE      5909
WA_FEMALE    5343
Name: (F4, 4, 2), dtype: int64

In [28]:
age_groups[3]

[9, 10]

In [32]:
census[census.YEAR == 1]

,SUMLEV,STATE,COUNTY,STNAME,CTYNAME,YEAR,AGEGRP,TOT_POP,TOT_MALE,TOT_FEMALE,...,HWAC_MALE,HWAC_FEMALE,HBAC_MALE,HBAC_FEMALE,HIAC_MALE,HIAC_FEMALE,HAAC_MALE,HAAC_FEMALE,HNAC_MALE,HNAC_FEMALE
0,50,1,1,Alabama,Autauga County,1,0,54571,26569,28002,...,607,538,57,48,26,32,9,11,19,10
1,50,1,1,Alabama,Autauga County,1,1,3579,1866,1713,...,77,56,9,5,4,1,0,0,2,1
2,50,1,1,Alabama,Autauga County,1,2,3991,2001,1990,...,64,66,2,3,2,7,2,3,2,0
3,50,1,1,Alabama,Autauga County,1,3,4290,2171,2119,...,51,57,13,7,5,5,2,1,1,1
4,50,1,1,Alabama,Autauga County,1,4,4290,2213,2077,...,48,44,7,5,0,2,2,1,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477446,50,56,45,Wyoming,Weston County,1,14,324,152,172,...,1,0,0,0,0,0,0,0,0,0
477447,50,56,45,Wyoming,Weston County,1,15,290,128,162,...,1,1,0,0,0,0,0,0,0,0
477448,50,56,45,Wyoming,Weston County,1,16,190,80,110,...,1,1,0,0,0,0,0,0,0,0
477449,50,56,45,Wyoming,Weston County,1,17,162,88,74,...,0,0,0,0,1,0,0,0,0,0
477450,50,56,45,Wyoming,Weston County,1,18,183,59,124,...,0,2,0,0,0,0,0,0,0,0

In [33]:
census[census.YEAR == 2]

,SUMLEV,STATE,COUNTY,STNAME,CTYNAME,YEAR,AGEGRP,TOT_POP,TOT_MALE,TOT_FEMALE,...,HWAC_MALE,HWAC_FEMALE,HBAC_MALE,HBAC_FEMALE,HIAC_MALE,HIAC_FEMALE,HAAC_MALE,HAAC_FEMALE,HNAC_MALE,HNAC_FEMALE
19,50,1,1,Alabama,Autauga County,2,0,54571,26569,28002,...,607,538,57,48,26,32,9,11,19,10
20,50,1,1,Alabama,Autauga County,2,1,3579,1866,1713,...,77,56,9,5,4,1,0,0,2,1
21,50,1,1,Alabama,Autauga County,2,2,3991,2001,1990,...,64,66,2,3,2,7,2,3,2,0
22,50,1,1,Alabama,Autauga County,2,3,4290,2171,2119,...,51,57,13,7,5,5,2,1,1,1
23,50,1,1,Alabama,Autauga County,2,4,4290,2213,2077,...,48,44,7,5,0,2,2,1,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477465,50,56,45,Wyoming,Weston County,2,14,324,152,172,...,1,0,0,0,0,0,0,0,0,0
477466,50,56,45,Wyoming,Weston County,2,15,290,128,162,...,1,1,0,0,0,0,0,0,0,0
477467,50,56,45,Wyoming,Weston County,2,16,190,80,110,...,1,1,0,0,0,0,0,0,0,0
477468,50,56,45,Wyoming,Weston County,2,17,162,88,74,...,0,0,0,0,1,0,0,0,0,0
477469,50,56,45,Wyoming,Weston County,2,18,183,59,124,...,0,2,0,0,0,0,0,0,0,0

In [34]:
census[census.YEAR == 3]

,SUMLEV,STATE,COUNTY,STNAME,CTYNAME,YEAR,AGEGRP,TOT_POP,TOT_MALE,TOT_FEMALE,...,HWAC_MALE,HWAC_FEMALE,HBAC_MALE,HBAC_FEMALE,HIAC_MALE,HIAC_FEMALE,HAAC_MALE,HAAC_FEMALE,HNAC_MALE,HNAC_FEMALE
38,50,1,1,Alabama,Autauga County,3,0,54660,26618,28042,...,616,548,60,46,21,28,13,10,19,11
39,50,1,1,Alabama,Autauga County,3,1,3576,1865,1711,...,79,55,10,6,4,0,2,0,1,0
40,50,1,1,Alabama,Autauga County,3,2,3958,1983,1975,...,65,64,3,3,3,6,0,0,0,0
41,50,1,1,Alabama,Autauga County,3,3,4290,2165,2125,...,53,56,11,9,5,5,3,2,2,2
42,50,1,1,Alabama,Autauga County,3,4,4145,2144,2001,...,45,43,7,6,0,1,2,0,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477484,50,56,45,Wyoming,Weston County,3,14,321,153,168,...,1,0,0,0,0,0,0,0,0,0
477485,50,56,45,Wyoming,Weston County,3,15,287,126,161,...,1,1,0,0,0,0,0,0,0,0
477486,50,56,45,Wyoming,Weston County,3,16,187,82,105,...,1,1,0,0,0,0,0,0,0,0
477487,50,56,45,Wyoming,Weston County,3,17,165,86,79,...,0,0,0,0,1,0,0,0,0,0
477488,50,56,45,Wyoming,Weston County,3,18,181,61,120,...,0,2,0,0,0,0,0,0,0,0

In [121]:
final_df.fillna(0)

        Race    Age Gender Location  Year  Count  Population
0      Asian  15–19      F       F4  2010    5.0       134.0
1      Asian  15–19      F       F4  2011    5.0       120.0
2      Asian  15–19      F       F4  2012    2.0       117.0
3      Asian  15–19      F       F4  2013    3.0       108.0
4      Asian  15–19      F       F4  2014    3.0       118.0
...      ...    ...    ...      ...   ...    ...         ...
16920  Other    50+      M       H6  2011  111.0         0.0
16921  Other    50+      M       H6  2012   66.0         0.0
16922  Other    50+      M       H6  2013   52.0         0.0
16923  Other    50+      M       H6  2014   45.0         0.0
16924  Other    50+      M       H6  2015   63.0         0.0

[16925 rows x 7 columns]

In [123]:
final_df = final_df[final_df['Race'] != 'Other']

In [125]:
final_df.to_csv('merged.csv', index=False)

In [120]:
final_df[(final_df['Location'] == 'A2') & (final_df['Race'] == 'Asian') & (final_df['Gender'] == 'M')]

       Race    Age Gender Location  Year  Count  Population
540   Asian  15–19      M       A2  2010    NaN         1.0
541   Asian  15–19      M       A2  2011    1.0         3.0
542   Asian  15–19      M       A2  2012    NaN         2.0
543   Asian  15–19      M       A2  2013    NaN         4.0
544   Asian  15–19      M       A2  2014    NaN         5.0
545   Asian  15–19      M       A2  2015    1.0         5.0
1224  Asian  20–29      M       A2  2010    8.0        17.0
1225  Asian  20–29      M       A2  2011    3.0        15.0
1226  Asian  20–29      M       A2  2012    7.0        15.0
1227  Asian  20–29      M       A2  2013    5.0        16.0
1228  Asian  20–29      M       A2  2014    4.0        15.0
1229  Asian  20–29      M       A2  2015    4.0        20.0
1908  Asian  30–39      M       A2  2010    3.0        28.0
1909  Asian  30–39      M       A2  2011    5.0        28.0
1910  Asian  30–39      M       A2  2012    3.0        29.0
1911  Asian  30–39      M       A2  2013    7.0        25.0
1912  Asian  30–39      M       A2  2014    1.0        24.0
1913  Asian  30–39      M       A2  2015    6.0        27.0
2592  Asian  40–49      M       A2  2010    9.0        22.0
2593  Asian  40–49      M       A2  2011    2.0        24.0
2594  Asian  40–49      M       A2  2012    4.0        23.0
2595  Asian  40–49      M       A2  2013    1.0        29.0
2596  Asian  40–49      M       A2  2014    2.0        34.0
2597  Asian  40–49      M       A2  2015    1.0        34.0
3276  Asian    50+      M       A2  2010    1.0        32.0
3277  Asian    50+      M       A2  2011    2.0        38.0
3278  Asian    50+      M       A2  2012    4.0        45.0
3279  Asian    50+      M       A2  2013    2.0        49.0
3280  Asian    50+      M       A2  2014    4.0        56.0
3281  Asian    50+      M       A2  2015    7.0        65.0